import assert from 'node:assert/strict'
import test from 'node:test'
import { ReportScheduleRunHandler, ReportScheduleScanner } from '../src/report-schedules'
import { LeasedWorkerJob } from '../../server/app/service/worker'
const tenant='00000000-0000-4000-8000-000000000001', project='00000000-0000-4000-8000-000000000002', schedule='00000000-0000-4000-8000-000000000003', run='00000000-0000-4000-8000-000000000004', target='00000000-0000-4000-8000-000000000005'
function job():LeasedWorkerJob{return{id:'00000000-0000-4000-8000-000000000006',tenant_id:tenant,project_id:project,kind:'report_schedule_run',idempotency_key:'x',payload:{report_run_id:run},watermark:{},lease_owner:'worker',lease_expires_at:new Date(),attempt_count:1,max_attempts:3,processed_count:0,failed_count:0}}
test('report schedule scanner locks due schedules, freezes a bounded definition and enqueues exactly one run job',async()=>{const calls:string[]=[];const c={async query<T=Record<string,unknown>>(text:string){calls.push(text);if(text==='BEGIN'||text==='COMMIT')return{rows:[] as T[],rowCount:0};if(text.includes('FROM report_schedules schedule'))return{rows:[{id:schedule,tenant_id:tenant,project_id:project,target_type:'insight',target_id:target,cadence:'daily',timezone:'UTC',next_run_at:new Date('2026-09-12T00:00:00Z'),notification_target_id:target}] as T[],rowCount:1};if(text.includes('FROM saved_insights'))return{rows:[{definition:{schema_version:1,kind:'funnel',subject_kind:'visitor',steps:['view','purchase'],from:'2026-09-01T00:00:00Z',to:'2026-09-02T00:00:00Z',timezone:'UTC'}}] as T[],rowCount:1};if(text.includes('INSERT INTO report_runs'))return{rows:[{id:run}] as T[],rowCount:1};return{rows:[] as T[],rowCount:1}},release(){}};const result=await new ReportScheduleScanner({async connect(){return c}} as never).scan();assert.equal(result.created,1);const inserted=calls.find(text=>text.includes('INSERT INTO report_runs'))??'';assert.match(inserted,/FOR UPDATE OF schedule SKIP LOCKED|ON CONFLICT\(schedule_id,scheduled_for\)/);assert.match(inserted,/report_schedule_run/);assert.doesNotMatch(inserted,/webhook|secret|email/i)})
test('report schedule run fails closed without a private artifact store',async()=>{const calls:string[]=[];const db={async query<T extends object>(text:string){calls.push(text);return{rows:[] as T[],rowCount:1}}};const result=await new ReportScheduleRunHandler(db).runJob(job());assert.equal(result.failedCount,1);assert.equal(result.watermark?.terminal_reason,'artifact_store_unavailable');assert.ok(calls.some(text=>text.includes("status='failed'")));assert.equal(calls.some(text=>text.includes('FROM events')),false)})
test('completed report run writes a private delivery outbox payload that contains only the delivery id',async()=>{const calls:string[]=[];const db={async query<T extends object>(text:string){calls.push(text);if(text.includes("SET status='running'"))return{rows:[{id:run,tenant_id:tenant,project_id:project,schedule_id:schedule,definition:{schema_version:1,kind:'funnel',subject_kind:'visitor',steps:['view','purchase'],from:'2026-09-01T00:00:00Z',to:'2026-09-02T00:00:00Z',timezone:'UTC'},format:'xlsx',notification_target_id:target}] as T[],rowCount:1};if(text.includes('FROM events'))return{rows:[] as T[],rowCount:0};if(text.includes('UPDATE report_runs SET status=\'completed\''))return{rows:[{id:run}] as T[],rowCount:1};return{rows:[] as T[],rowCount:1}}};const store={async put(){return{ref:'report-run/00000000-0000-4000-8000-000000000007.xlsx',byteCount:3}},async read(){return null},async remove(){}};const result=await new ReportScheduleRunHandler(db,store).runJob(job());assert.equal(result.failedCount,0);const queued=calls.find(text=>text.includes("'report_run_delivery'"))??'';assert.match(queued,/jsonb_build_object\('report_run_delivery_id',id\)/);assert.doesNotMatch(queued.slice(queued.indexOf("jsonb_build_object")),/artifact_ref|webhook|secret/i)})
