import { createHash, randomUUID } from 'node:crypto'
import { DatabaseClient, PostgreSqlConnection } from '../../server/app/service/database/types'
import { PrivateExportArtifactStore } from '../../server/app/service/reporting/artifacts'
import { renderAggregateExport } from '../../server/app/service/reporting/exporter'
import type { DashboardExportPlan } from '../../server/app/service/reporting'
import { parseDefinition } from '../../server/app/service/insights/contracts'
import { LeasedWorkerJob, WorkerHandlers } from '../../server/app/service/worker'

type TransactionDriver = DatabaseClient & { connect(): Promise<PostgreSqlConnection> }
type DueSchedule = { id:string; tenant_id:string; project_id:string; target_type:'insight'|'dashboard'; target_id:string; cadence:'daily'|'weekly'|'monthly'; timezone:string; next_run_at:Date; notification_target_id:string }
type FrozenRun = { id:string; tenant_id:string; project_id:string; schedule_id:string; definition:Record<string,unknown>; format:'csv'|'xlsx'; notification_target_id:string }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i

/** The scanner is explicit worker work.  It locks due rows, freezes only current project-visible aggregate definitions, then creates a unique run/job pair. */
export class ReportScheduleScanner {
  constructor(private readonly database:TransactionDriver) {}
  async scan(limit=25):Promise<{created:number;disabled:number}> {
    if(!Number.isSafeInteger(limit)||limit<1||limit>100)throw new Error('invalid_report_schedule_scan_limit')
    return this.transaction(async db=>{
      const due=await db.query<DueSchedule>(`SELECT schedule.id,schedule.tenant_id,schedule.project_id,schedule.target_type,schedule.target_id,schedule.cadence,schedule.timezone,schedule.next_run_at,schedule.notification_target_id FROM report_schedules schedule JOIN projects project ON project.tenant_id=schedule.tenant_id AND project.id=schedule.project_id AND project.deletion_status='active' JOIN notification_targets target ON target.tenant_id=schedule.tenant_id AND target.project_id=schedule.project_id AND target.id=schedule.notification_target_id AND target.enabled AND target.verified_at IS NOT NULL AND target.disabled_at IS NULL WHERE schedule.enabled AND schedule.next_run_at<=now() ORDER BY schedule.next_run_at ASC,schedule.id ASC FOR UPDATE OF schedule SKIP LOCKED LIMIT $1`,[limit])
      let created=0,disabled=0
      for(const schedule of due.rows){
        const definition=await freezeDefinition(db,schedule)
        if(!definition){await db.query(`UPDATE report_schedules SET enabled=false,updated_at=now() WHERE id=$1 AND tenant_id=$2 AND project_id=$3`,[schedule.id,schedule.tenant_id,schedule.project_id]);await audit(db,schedule,'report_schedule_disabled_unavailable_target');disabled++;continue}
        const runId=randomUUID();const next=nextRun(schedule.next_run_at,schedule.cadence,schedule.timezone)
        const inserted=await db.query<{id:string}>(`WITH run AS (INSERT INTO report_runs (id,tenant_id,project_id,schedule_id,scheduled_for,status,definition,query_hash,format) VALUES ($1,$2,$3,$4,$5,'queued',$6::jsonb,$7,$8) ON CONFLICT(schedule_id,scheduled_for) DO NOTHING RETURNING id), advanced AS (UPDATE report_schedules SET next_run_at=$9,updated_at=now() WHERE id=$4 AND tenant_id=$2 AND project_id=$3 AND enabled RETURNING id), job AS (INSERT INTO worker_jobs (id,tenant_id,project_id,kind,idempotency_key,payload,max_attempts) SELECT $10,$2,$3,'report_schedule_run','report-schedule-run:'||id,jsonb_build_object('report_run_id',id),3 FROM run ON CONFLICT(tenant_id,project_id,kind,idempotency_key) DO NOTHING RETURNING id) SELECT id FROM run`,[runId,schedule.tenant_id,schedule.project_id,schedule.id,schedule.next_run_at,JSON.stringify(definition),createHash('sha256').update(JSON.stringify(definition)).digest(),'xlsx',next,randomUUID()])
        if(inserted.rows[0]){created++;await audit(db,schedule,'report_run_queued',{run_id:runId})}
      }
      return {created,disabled}
    })
  }
  private async transaction<T>(fn:(db:PostgreSqlConnection)=>Promise<T>):Promise<T>{const db=await this.database.connect();try{await db.query('BEGIN');const value=await fn(db);await db.query('COMMIT');return value}catch(error){try{await db.query('ROLLBACK')}catch{}throw error}finally{db.release()}}
}

/** Executes one previously frozen schedule run. Missing storage or any fresh authorization/target failure is terminal and emits no outbound data. */
export class ReportScheduleRunHandler implements Pick<WorkerHandlers,'runJob'> {
  constructor(private readonly database:DatabaseClient,private readonly artifacts?:PrivateExportArtifactStore){}
  async runJob(job:LeasedWorkerJob):Promise<{processedCount:number;failedCount:number;watermark?:Record<string,unknown>}>{
    if(job.kind!=='report_schedule_run')throw new Error(`unsupported_worker_job:${job.kind}`)
    const runId=runIdOf(job.payload.report_run_id);const scope={tenantId:job.tenant_id,projectId:job.project_id}
    if(!this.artifacts){await fail(this.database,scope,runId,'artifact_store_unavailable');return {processedCount:0,failedCount:1,watermark:{terminal_reason:'artifact_store_unavailable'}}}
    const run=await claim(this.database,scope,runId);if(!run)return {processedCount:0,failedCount:0,watermark:{skipped:'run_not_queued_or_unavailable'}}
    try { const definition=scheduledDefinition(run.definition);const rendered=await renderAggregateExport(this.database,scope,definition,run.format);const artifact=await this.artifacts.put({tenantId:scope.tenantId,projectId:scope.projectId,jobId:runId,format:run.format,contents:rendered.contents,kind:'report-run'});if(!await completeAndQueue(this.database,scope,run,artifact.ref,rendered.rowCount,artifact.byteCount)){await this.artifacts.remove(artifact.ref);return {processedCount:0,failedCount:0,watermark:{skipped:'run_state_changed'}}};return {processedCount:rendered.rowCount,failedCount:0,watermark:{report_run_id:runId,byte_count:artifact.byteCount}} }
    catch(error){const code=safeCode(error);await fail(this.database,scope,runId,code);return {processedCount:0,failedCount:1,watermark:{report_run_id:runId,terminal_reason:code}}}
  }
}
async function freezeDefinition(db:DatabaseClient,s:DueSchedule):Promise<Record<string,unknown>|null>{
  if(s.target_type==='insight'){const r=await db.query<{definition:Record<string,unknown>}>(`SELECT definition FROM saved_insights WHERE tenant_id=$1 AND project_id=$2 AND id=$3 AND archived_at IS NULL AND visibility='project'`,[s.tenant_id,s.project_id,s.target_id]);if(!r.rows[0])return null;try{return parseDefinition(r.rows[0].definition) as Record<string,unknown>}catch{return null}}
  const r=await db.query<{name:string;definitions:Array<{name:string;definition:Record<string,unknown>}>}>(`SELECT dashboard.name,COALESCE(jsonb_agg(jsonb_build_object('name',COALESCE(tile.title_override,insight.name),'definition',insight.definition) ORDER BY tile.position) FILTER (WHERE tile.id IS NOT NULL),'[]'::jsonb) AS definitions FROM dashboards dashboard LEFT JOIN dashboard_tiles tile ON tile.tenant_id=dashboard.tenant_id AND tile.project_id=dashboard.project_id AND tile.dashboard_id=dashboard.id LEFT JOIN saved_insights insight ON insight.tenant_id=tile.tenant_id AND insight.project_id=tile.project_id AND insight.id=tile.saved_insight_id AND insight.archived_at IS NULL AND insight.visibility='project' WHERE dashboard.tenant_id=$1 AND dashboard.project_id=$2 AND dashboard.id=$3 AND dashboard.archived_at IS NULL GROUP BY dashboard.id,dashboard.name`,[s.tenant_id,s.project_id,s.target_id]);const row=r.rows[0];if(!row||!Array.isArray(row.definitions)||row.definitions.length===0)return null;try{const definitions=row.definitions.map(item=>({name:typeof item.name==='string'?item.name:'analysis',definition:parseDefinition(item.definition)}));return {export_plan:'dashboard',name:row.name,definitions}}catch{return null}}
async function claim(db:DatabaseClient,scope:{tenantId:string;projectId:string},id:string):Promise<FrozenRun|null>{const result=await db.query<FrozenRun>(`UPDATE report_runs run SET status='running',started_at=COALESCE(started_at,now()),error_code=NULL FROM report_schedules schedule JOIN projects project ON project.tenant_id=schedule.tenant_id AND project.id=schedule.project_id AND project.deletion_status='active' JOIN notification_targets target ON target.tenant_id=schedule.tenant_id AND target.project_id=schedule.project_id AND target.id=schedule.notification_target_id AND target.enabled AND target.verified_at IS NOT NULL AND target.disabled_at IS NULL WHERE run.id=$3 AND run.tenant_id=$1 AND run.project_id=$2 AND run.schedule_id=schedule.id AND schedule.tenant_id=$1 AND schedule.project_id=$2 AND schedule.enabled AND run.status='queued' RETURNING run.id,run.tenant_id,run.project_id,run.schedule_id,run.definition,run.format,schedule.notification_target_id`,[scope.tenantId,scope.projectId,id]);return result.rows[0]??null}
async function completeAndQueue(db:DatabaseClient,scope:{tenantId:string;projectId:string},run:FrozenRun,ref:string,rowCount:number,byteCount:number):Promise<boolean>{const delivery=randomUUID();const result=await db.query(`WITH completed AS (UPDATE report_runs SET status='completed',artifact_ref=$4,row_count=$5,byte_count=$6,delivery_id=$7,finished_at=now(),error_code=NULL WHERE id=$3 AND tenant_id=$1 AND project_id=$2 AND status='running' RETURNING id), delivery AS (INSERT INTO report_run_deliveries (id,tenant_id,project_id,report_run_id,target_id) SELECT $7,$1,$2,id,$8 FROM completed ON CONFLICT(report_run_id,target_id) DO NOTHING RETURNING id), outbox AS (INSERT INTO outbox_messages (id,tenant_id,project_id,topic,idempotency_key,payload,max_attempts) SELECT $9,$1,$2,'report_run_delivery','report-run-delivery:'||id,jsonb_build_object('report_run_delivery_id',id),5 FROM delivery ON CONFLICT(tenant_id,project_id,topic,idempotency_key) DO NOTHING RETURNING id) SELECT id FROM completed`,[scope.tenantId,scope.projectId,run.id,ref,rowCount,byteCount,delivery,run.notification_target_id,randomUUID()]);return result.rowCount===1}
async function fail(db:DatabaseClient,scope:{tenantId:string;projectId:string},id:string,code:string){await db.query(`UPDATE report_runs SET status='failed',error_code=$4,finished_at=now() WHERE id=$3 AND tenant_id=$1 AND project_id=$2 AND status IN('queued','running')`,[scope.tenantId,scope.projectId,id,code])}
function scheduledDefinition(value:Record<string,unknown>){if(value.export_plan==='dashboard'){if(typeof value.name!=='string'||!Array.isArray(value.definitions)||value.definitions.length<1||value.definitions.length>24)throw new Error('invalid_export_definition');return {export_plan:'dashboard' as const,name:value.name,definitions:value.definitions.map(item=>{if(!item||typeof item!=='object'||Array.isArray(item)||typeof (item as Record<string,unknown>).name!=='string')throw new Error('invalid_export_definition');return {name:(item as Record<string,unknown>).name as string,definition:parseDefinition((item as Record<string,unknown>).definition)}})} as DashboardExportPlan};return parseDefinition(value)}
function runIdOf(value:unknown){if(typeof value!=='string'||!UUID.test(value))throw new Error('invalid_report_run_payload');return value};function safeCode(error:unknown){const msg=error instanceof Error?error.message:'';return ['export_limit_exceeded','invalid_export_definition'].includes(msg)?msg:'report_run_execution_failed'}
function nextRun(previous:Date,cadence:'daily'|'weekly'|'monthly',timeZone:string):Date { const step=cadence==='daily'?86_400_000:cadence==='weekly'?7*86_400_000:31*86_400_000; const next=new Date(previous.getTime()+step); if(!Number.isFinite(next.getTime()))throw new Error('invalid_report_schedule_time'); try{Intl.DateTimeFormat('en-US',{timeZone}).format(next)}catch{throw new Error('invalid_report_schedule_timezone')} return next }
async function audit(db:DatabaseClient,s:DueSchedule,action:string,metadata:Record<string,unknown>={}){await db.query(`INSERT INTO audit_logs (id,tenant_id,action,target_type,target_id,metadata) VALUES ($1,$2,$3,'report_schedule',$4,$5::jsonb)`,[randomUUID(),s.tenant_id,action,s.id,JSON.stringify(metadata)])}
