import { Service } from 'egg'
import { httpError } from '../../lib/http'
import { CohortScope, parseCohortInput, parseCohortUpdate, parsePreview, queryHash, snapshotRange } from './contracts'
import { CohortRow, CohortsRepository, SnapshotRow } from './repository'
export class CohortsManagementService {
  constructor(private readonly database: import('../database/types').DatabaseClient) {}
  async list(scope:CohortScope,actor:string){return{items:(await new CohortsRepository(this.database).list(scope,actor)).map(dto)}}
  async show(scope:CohortScope,actor:string,id:string){return dto(await this.readable(scope,actor,id))}
  async create(scope:CohortScope,actor:string,manage:boolean,raw:unknown){const input=parseCohortInput(raw);if(input.visibility==='project'&&!manage)throw forbidden();return dto(await new CohortsRepository(this.database).create(scope,actor,input))}
  async update(scope:CohortScope,actor:string,manage:boolean,id:string,raw:unknown){await this.editable(scope,actor,manage,id);const input=parseCohortUpdate(raw);if(input.visibility==='project'&&!manage)throw forbidden();const row=await new CohortsRepository(this.database).update(scope,id,actor,input,input.expectedDefinitionVersion);if(row)return dto(row);const latest=await new CohortsRepository(this.database).get(scope,id);if(!latest)throw missing();throw conflict(latest)}
  async archive(scope:CohortScope,actor:string,manage:boolean,id:string,expected:number){await this.editable(scope,actor,manage,id);if(!Number.isSafeInteger(expected)||expected<1)throw httpError(400,'invalid_cohort','Cohort is invalid');if(await new CohortsRepository(this.database).archive(scope,id,actor,expected))return{archived:true};const latest=await new CohortsRepository(this.database).get(scope,id);if(!latest)throw missing();throw conflict(latest)}
  async preview(scope:CohortScope,actor:string,id:string,raw:unknown,now=new Date()){const cohort=await this.readable(scope,actor,id);const asOf=parsePreview(raw,now).asOf;const range=snapshotRange(cohort.definition,asOf);const snapshot=await new CohortsRepository(this.database).preview(scope,cohort,range,queryHash(cohort.subject_kind,cohort.definition,range));return{cohort_id:cohort.id,definition_version:cohort.definition_version,snapshot:snapshotDto(snapshot),identity_attribution:'all_linked',facts_deduplicated:true}}
  private async readable(scope:CohortScope,actor:string,id:string){const row=await new CohortsRepository(this.database).get(scope,id);if(!row||(row.visibility==='private'&&row.created_by!==actor))throw missing();return row}
  private async editable(scope:CohortScope,actor:string,manage:boolean,id:string){const row=await this.readable(scope,actor,id);if(row.visibility==='project'&&!manage)throw forbidden();return row}
}
export default class CohortsService extends Service { private domain(){const db=this.config.zhiji.database;if(!db?.configured)throw httpError(503,'cohorts_unavailable','Cohorts are unavailable');return new CohortsManagementService(db)} list(s:CohortScope,a:string){return this.domain().list(s,a)} show(s:CohortScope,a:string,id:string){return this.domain().show(s,a,id)} create(s:CohortScope,a:string,m:boolean,r:unknown){return this.domain().create(s,a,m,r)} update(s:CohortScope,a:string,m:boolean,id:string,r:unknown){return this.domain().update(s,a,m,id,r)} archive(s:CohortScope,a:string,m:boolean,id:string,v:number){return this.domain().archive(s,a,m,id,v)} preview(s:CohortScope,a:string,id:string,r:unknown){return this.domain().preview(s,a,id,r)} }
function dto(row:CohortRow){return{id:row.id,name:row.name,description:row.description,subject_kind:row.subject_kind,definition:row.definition,definition_version:row.definition_version,visibility:row.visibility,created_by:row.created_by,updated_by:row.updated_by,created_at:row.created_at.toISOString(),updated_at:row.updated_at.toISOString()}}
function snapshotDto(row:SnapshotRow){return{id:row.id,cohort_id:row.cohort_id,definition_version:row.definition_version,calculated_at:row.calculated_at.toISOString(),range_from:row.range_from.toISOString(),range_to:row.range_to.toISOString(),subject_kind:row.subject_kind,member_count:Number(row.member_count),expires_at:row.expires_at.toISOString(),members_available:false}}
function missing():never{throw httpError(404,'resource_not_found','Resource was not found')}function forbidden():never{throw httpError(403,'forbidden','Permission is denied')}function conflict(row:CohortRow):ReturnType<typeof httpError>{return httpError(409,'cohort_version_conflict','Cohort has changed',{current_definition_version:String(row.definition_version),current_name:row.name})}
