import { randomUUID } from 'node:crypto'
import { DatabaseClient } from '../database/types'
import { CohortDefinition, CohortInput, CohortScope, SubjectKind, Visibility } from './contracts'
export interface CohortRow { id: string; name: string; description: string | null; subject_kind: SubjectKind; definition: CohortDefinition; definition_version: number; visibility: Visibility; created_by: string; updated_by: string; created_at: Date; updated_at: Date; archived_at: Date | null }
export interface SnapshotRow { id: string; cohort_id: string; definition_version: number; calculated_at: Date; range_from: Date; range_to: Date; subject_kind: SubjectKind; member_count: number; query_hash: Buffer; expires_at: Date }
export class CohortsRepository {
  constructor(private readonly database: DatabaseClient) {}
  async list(scope: CohortScope, actorId: string): Promise<CohortRow[]> { const result = await this.database.query<CohortRow>(`SELECT id,name,description,subject_kind,definition,definition_version,visibility,created_by,updated_by,created_at,updated_at,archived_at FROM cohorts WHERE tenant_id=$1 AND project_id=$2 AND archived_at IS NULL AND (visibility='project' OR created_by=$3) ORDER BY created_at DESC,id DESC LIMIT 200`, [ scope.tenantId, scope.projectId, actorId ]); return result.rows }
  async get(scope: CohortScope, id: string): Promise<CohortRow | null> { const result = await this.database.query<CohortRow>(`SELECT id,name,description,subject_kind,definition,definition_version,visibility,created_by,updated_by,created_at,updated_at,archived_at FROM cohorts WHERE tenant_id=$1 AND project_id=$2 AND id=$3 AND archived_at IS NULL`, [ scope.tenantId, scope.projectId, id ]); return result.rows[0] ?? null }
  async create(scope: CohortScope, actorId: string, input: CohortInput): Promise<CohortRow> { const id=randomUUID(); const result=await this.database.query<CohortRow>(`WITH inserted AS (INSERT INTO cohorts (id,tenant_id,project_id,name,description,subject_kind,definition,visibility,created_by,updated_by) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$9) RETURNING id,name,description,subject_kind,definition,definition_version,visibility,created_by,updated_by,created_at,updated_at,archived_at), audit AS (INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,metadata) SELECT $10,$2,$9,'cohort_created','cohort',$1,jsonb_build_object('visibility',$8,'subject_kind',$6) FROM inserted) SELECT * FROM inserted`,[id,scope.tenantId,scope.projectId,input.name,input.description,input.subjectKind,JSON.stringify(input.definition),input.visibility,actorId,randomUUID()]);const row=result.rows[0];if(!row)throw new Error('cohort creation failed');return row }
  async update(scope:CohortScope,id:string,actor:string,input:CohortInput,expected:number):Promise<CohortRow|null>{const result=await this.database.query<CohortRow>(`WITH updated AS (UPDATE cohorts SET name=$4,description=$5,subject_kind=$6,definition=$7::jsonb,visibility=$8,definition_version=definition_version+1,updated_by=$9,updated_at=now() WHERE tenant_id=$1 AND project_id=$2 AND id=$3 AND archived_at IS NULL AND definition_version=$10 RETURNING id,name,description,subject_kind,definition,definition_version,visibility,created_by,updated_by,created_at,updated_at,archived_at), audit AS (INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,metadata) SELECT $11,$1,$9,'cohort_updated','cohort',$3,jsonb_build_object('definition_version',definition_version) FROM updated) SELECT * FROM updated`,[scope.tenantId,scope.projectId,id,input.name,input.description,input.subjectKind,JSON.stringify(input.definition),input.visibility,actor,expected,randomUUID()]);return result.rows[0]??null}
  async archive(scope:CohortScope,id:string,actor:string,expected:number):Promise<boolean>{const result=await this.database.query(`WITH updated AS (UPDATE cohorts SET archived_at=now(),updated_by=$4,updated_at=now(),definition_version=definition_version+1 WHERE tenant_id=$1 AND project_id=$2 AND id=$3 AND archived_at IS NULL AND definition_version=$5 RETURNING id), audit AS (INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,metadata) SELECT $6,$1,$4,'cohort_archived','cohort',$3,'{}'::jsonb FROM updated) SELECT id FROM updated`,[scope.tenantId,scope.projectId,id,actor,expected,randomUUID()]);return result.rowCount===1}
  async preview(scope:CohortScope, cohort:CohortRow, range:{from:Date;to:Date}, hash:Buffer):Promise<SnapshotRow>{
    const p=cohort.definition.property_filters??[]; const source=cohort.subject_kind==='visitor'
      ? `SELECT e.id, e.visitor_id AS subject_id FROM scoped_events e`
      : `SELECT DISTINCT e.id, i.business_user_id AS subject_id FROM scoped_events e JOIN identities i ON i.tenant_id=$1 AND i.project_id=$2 AND i.visitor_id=e.visitor_id`
    const result=await this.database.query<SnapshotRow>(`WITH scoped_events AS (SELECT id,visitor_id FROM events e WHERE e.tenant_id=$1 AND e.project_id=$2 AND e.name=$3 AND e.occurred_at >= $4 AND e.occurred_at < $5 AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements($6::jsonb) f WHERE NOT (e.properties ? (f->>'key') AND e.properties -> (f->>'key') = f->'value'))), subjects AS (${source}), qualified AS (SELECT subject_id FROM subjects GROUP BY subject_id HAVING COUNT(DISTINCT id) >= $7 AND ($8::integer IS NULL OR COUNT(DISTINCT id) <= $8)), count_row AS (SELECT COUNT(*)::bigint AS member_count FROM qualified), inserted AS (INSERT INTO cohort_snapshots (id,tenant_id,project_id,cohort_id,definition_version,range_from,range_to,subject_kind,member_count,query_hash,expires_at) SELECT $9,$1,$2,$10,$11,$4,$5,$12,member_count,$13,now()+interval '30 days' FROM count_row ON CONFLICT (tenant_id,project_id,cohort_id,definition_version,range_from,range_to) DO UPDATE SET calculated_at=now(),member_count=EXCLUDED.member_count,query_hash=EXCLUDED.query_hash,expires_at=EXCLUDED.expires_at RETURNING id,cohort_id,definition_version,calculated_at,range_from,range_to,subject_kind,member_count,query_hash,expires_at) SELECT * FROM inserted`, [scope.tenantId,scope.projectId,cohort.definition.event_name,range.from,range.to,JSON.stringify(p),cohort.definition.min_occurrences,cohort.definition.max_occurrences??null,randomUUID(),cohort.id,cohort.definition_version,cohort.subject_kind,hash]);const row=result.rows[0];if(!row)throw new Error('cohort snapshot failed');return row
  }
  async cleanupExpired(limit:number):Promise<number>{const result=await this.database.query<{id:string}>(`WITH doomed AS (SELECT id FROM cohort_snapshots WHERE expires_at <= now() ORDER BY expires_at ASC,id ASC LIMIT $1 FOR UPDATE SKIP LOCKED), deleted AS (DELETE FROM cohort_snapshots s USING doomed WHERE s.id=doomed.id RETURNING s.id) SELECT id FROM deleted`,[limit]);return result.rowCount ?? 0}
}
