import { Service } from 'egg'
import { httpError } from '../../lib/http'
import { DatabaseClient } from '../database/types'
import { AlertsRepository, AlertInstanceListRecord, AlertRuleListRecord, NotificationDeliveryListRecord, NotificationTargetListRecord } from './repository'
import { alertCursorFor, AlertScope, parseAlertListQuery, parseExpectedUpdatedAt, parseRuleInput, parseRulePatch, parseTargetInput, parseTargetPatch, scrubAlertSummary, validateCondition } from './contracts'

export class AlertsManagementService {
  constructor(private readonly database: DatabaseClient) {}
  async createTarget(scope: AlertScope, actorId: string, raw: unknown) { return targetDto(await new AlertsRepository(this.database).createDisabledTarget(scope, actorId, parseTargetInput(raw))) }
  async updateTarget(scope: AlertScope, id: string, actorId: string, raw: unknown) { const target=await new AlertsRepository(this.database).updateTarget(scope,id,actorId,parseTargetPatch(raw));if(!target) throw httpError(409,'alert_target_state_conflict','Notification target changed, is unverified, or was not found');return targetDto(target) }
  async disableTarget(scope: AlertScope, id: string, actorId: string, raw: unknown) { if(!await new AlertsRepository(this.database).disableTarget(scope,id,actorId,parseExpectedUpdatedAt(raw))) throw httpError(409,'alert_target_state_conflict','Notification target changed, is already disabled, or was not found'); return { id, disabled: true } }
  async createRule(scope: AlertScope, actorId: string, raw: unknown) { const input=parseRuleInput(raw); try { return await new AlertsRepository(this.database).createRule(scope,actorId,input) } catch(error) { if(error instanceof Error && error.message==='alert_rule_targets_unavailable') throw httpError(409,'alert_rule_targets_unavailable','Alert rule requires enabled verified scoped targets'); throw error } }
  async updateRule(scope: AlertScope, id: string, actorId: string, raw: unknown) {
    const repository=new AlertsRepository(this.database); const patch=parseRulePatch(raw); const current=await repository.findRule(scope,id); if(!current) throw httpError(404,'resource_not_found','Alert rule was not found')
    const condition=patch.condition ?? current.condition_json; validateCondition(current.rule_type,condition)
    const input={name:patch.name ?? current.name,ruleType:current.rule_type,condition,targetIds:patch.targetIds ?? current.target_ids,enabled:patch.enabled ?? current.enabled}
    const row=await repository.updateRule(scope,id,actorId,input,patch.expectedUpdatedAt);if(!row)throw httpError(409,'alert_rule_state_conflict','Alert rule changed or a linked target is unavailable');return ruleDto(row)
  }
  async disableRule(scope: AlertScope, id: string, actorId: string, raw: unknown) { if(!await new AlertsRepository(this.database).disableRule(scope,id,actorId,parseExpectedUpdatedAt(raw))) throw httpError(409,'alert_rule_state_conflict','Alert rule changed, is already disabled, or was not found');return {id,disabled:true} }
  async listTargets(scope: AlertScope, raw: unknown) { const query=parseAlertListQuery(raw);return page(await new AlertsRepository(this.database).listTargets(scope,query),query.limit,targetDto) }
  async listRules(scope: AlertScope, raw: unknown) { const query=parseAlertListQuery(raw);return page(await new AlertsRepository(this.database).listRules(scope,query),query.limit,ruleDto) }
  async listInstances(scope: AlertScope, raw: unknown) { const query=parseAlertListQuery(raw);return page(await new AlertsRepository(this.database).listInstances(scope,query),query.limit,instanceDto) }
  async listDeliveries(scope: AlertScope, raw: unknown) { const query=parseAlertListQuery(raw);return page(await new AlertsRepository(this.database).listDeliveries(scope,query),query.limit,deliveryDto) }
  safeSummary(raw: unknown) { return scrubAlertSummary(raw) }
}
export default class AlertsService extends Service {
  private domain(): AlertsManagementService { const database=this.config.zhiji.database;if(!database?.configured)throw httpError(503,'alerts_unavailable','Alerts are unavailable');return new AlertsManagementService(database) }
  createTarget(scope:AlertScope,actorId:string,raw:unknown){return this.domain().createTarget(scope,actorId,raw)};updateTarget(scope:AlertScope,id:string,actorId:string,raw:unknown){return this.domain().updateTarget(scope,id,actorId,raw)};disableTarget(scope:AlertScope,id:string,actorId:string,raw:unknown){return this.domain().disableTarget(scope,id,actorId,raw)}
  createRule(scope:AlertScope,actorId:string,raw:unknown){return this.domain().createRule(scope,actorId,raw)};updateRule(scope:AlertScope,id:string,actorId:string,raw:unknown){return this.domain().updateRule(scope,id,actorId,raw)};disableRule(scope:AlertScope,id:string,actorId:string,raw:unknown){return this.domain().disableRule(scope,id,actorId,raw)}
  listTargets(scope:AlertScope,query:unknown){return this.domain().listTargets(scope,query)};listRules(scope:AlertScope,query:unknown){return this.domain().listRules(scope,query)};listInstances(scope:AlertScope,query:unknown){return this.domain().listInstances(scope,query)};listDeliveries(scope:AlertScope,query:unknown){return this.domain().listDeliveries(scope,query)}
}
function page<T extends {created_at:Date;id:string},D>(rows:T[],limit:number,dto:(row:T)=>D){const items=rows.slice(0,limit);const last=items.at(-1);return {items:items.map(dto),next_cursor:rows.length>limit&&last?alertCursorFor(last.created_at,last.id):null}}
function targetDto(row:NotificationTargetListRecord){return{id:row.id,type:row.type,label:safeTargetLabel(row.label,row.type),enabled:row.enabled,verified_at:iso(row.verified_at),created_at:row.created_at.toISOString(),updated_at:row.updated_at.toISOString(),disabled_at:iso(row.disabled_at)}}
function ruleDto(row:AlertRuleListRecord){return{id:row.id,name:row.name,enabled:row.enabled,rule_type:row.rule_type,condition:safeCondition(row.rule_type,row.condition_json),target_ids:row.target_ids,targets_version:row.targets_version,created_at:row.created_at.toISOString(),updated_at:row.updated_at.toISOString()}}
function instanceDto(row:AlertInstanceListRecord){return{id:row.id,rule:{id:row.rule_id,name:row.rule_name,type:row.rule_type},status:row.status,first_triggered_at:row.first_triggered_at.toISOString(),last_triggered_at:row.last_triggered_at.toISOString(),last_evaluated_at:row.last_evaluated_at.toISOString(),cooldown_until:row.cooldown_until.toISOString(),summary:scrubAlertSummary(row.payload_summary)}}
function deliveryDto(row:NotificationDeliveryListRecord){return{id:row.id,alert_instance_id:row.alert_instance_id,target:{id:row.target_id,type:row.target_type,label:safeTargetLabel(row.target_label,row.target_type)},status:row.status,attempt_count:row.attempt_count,last_attempt_at:iso(row.last_attempt_at),delivered_at:iso(row.delivered_at),error_code:safeCode(row.last_error_code),created_at:row.created_at.toISOString()}}
function iso(value:Date|null){return value?.toISOString()??null};function safeTargetLabel(label:string,type:string){return /(?:https?:\/\/|\b[\w.+-]+@[\w-]+\.[\w.-]+\b)/i.test(label)?`${type} target`:label};function safeCondition(type:string,raw:Record<string,unknown>){const condition:Record<string,number|string>={};if(type==='error_new'||type==='error_regression')return condition;if(typeof raw.window_seconds==='number'&&[300,900,3600,86400].includes(raw.window_seconds))condition.window_seconds=raw.window_seconds;if(typeof raw.threshold==='number'&&Number.isFinite(raw.threshold)&&raw.threshold>0)condition.threshold=raw.threshold;if(type.startsWith('performance_')&&typeof raw.minimum_samples==='number'&&Number.isSafeInteger(raw.minimum_samples)&&raw.minimum_samples>=1)condition.minimum_samples=raw.minimum_samples;if(type.startsWith('performance_')&&typeof raw.metric==='string'&&['CLS','INP','LCP','FCP','TTFB'].includes(raw.metric))condition.metric=raw.metric;return condition};function safeCode(value:string|null){return value&&/^[a-z0-9_]{1,100}$/.test(value)?value:null}
