import { randomUUID } from 'node:crypto'
import { DatabaseClient } from '../database/types'
import { AlertListQuery, AlertRuleInput, AlertRuleType, AlertScope, AlertTargetPatch, NotificationType, SafeAlertSummary } from './contracts'

export interface NotificationTargetListRecord { id: string; type: NotificationType; label: string; enabled: boolean; verified_at: Date | null; created_at: Date; updated_at: Date; disabled_at: Date | null }
export interface AlertRuleListRecord { id: string; name: string; enabled: boolean; rule_type: AlertRuleType; condition_json: Record<string, unknown>; targets_version: number; target_ids: string[]; created_at: Date; updated_at: Date }
export interface AlertInstanceListRecord { id: string; rule_id: string; rule_name: string; rule_type: AlertRuleType; group_key: string; status: string; first_triggered_at: Date; last_triggered_at: Date; last_evaluated_at: Date; cooldown_until: Date; payload_summary: Record<string, unknown>; created_at: Date }
export interface NotificationDeliveryListRecord { id: string; alert_instance_id: string; target_id: string; target_type: NotificationType; target_label: string; status: string; attempt_count: number; last_attempt_at: Date | null; delivered_at: Date | null; last_error_code: string | null; created_at: Date }

export class AlertsRepository {
  constructor(private readonly database: DatabaseClient) {}
  async createRule(scope: AlertScope, actorId: string, input: AlertRuleInput): Promise<{ id: string }> {
    const id = randomUUID(); const result = await this.database.query<{ id: string }>(
      `WITH enabled_targets AS (SELECT id FROM notification_targets WHERE tenant_id=$1 AND project_id=$2 AND id=ANY($6::uuid[]) AND enabled AND verified_at IS NOT NULL AND disabled_at IS NULL),
       created AS (INSERT INTO alert_rules (id,tenant_id,project_id,name,enabled,rule_type,condition_json,created_by) SELECT $3,$1,$2,$4,$8,$5,$7::jsonb,$9 WHERE (SELECT count(*) FROM enabled_targets)=cardinality($6::uuid[]) RETURNING id),
       links AS (INSERT INTO alert_rule_targets (rule_id,target_id) SELECT created.id,enabled_targets.id FROM created CROSS JOIN enabled_targets),
       audit AS (INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,metadata) SELECT $10,$1,$9,'alert_rule_created','alert_rule',id,jsonb_build_object('rule_type',$5,'target_count',cardinality($6::uuid[])) FROM created)
       SELECT id FROM created`,
      [ scope.tenantId, scope.projectId, id, input.name, input.ruleType, input.targetIds, JSON.stringify(input.condition), input.enabled, actorId, randomUUID() ],
    ); const row = result.rows[0]; if (!row) throw new Error('alert_rule_targets_unavailable'); return row
  }
  async createDisabledTarget(scope: AlertScope, actorId: string, input: { type: NotificationType; label: string }): Promise<NotificationTargetListRecord> {
    const result = await this.database.query<NotificationTargetListRecord>(`WITH created AS (INSERT INTO notification_targets (id,tenant_id,project_id,type,label,enabled,config_public,created_by) VALUES ($1,$2,$3,$4,$5,false,'{}'::jsonb,$6) RETURNING id,type,label,enabled,verified_at,created_at,updated_at,disabled_at), audit AS (INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,metadata) SELECT $7,$2,$6,'notification_target_created','notification_target',$1,jsonb_build_object('type',$4) FROM created) SELECT * FROM created`, [ randomUUID(), scope.tenantId, scope.projectId, input.type, input.label, actorId, randomUUID() ]); const row = result.rows[0]; if (!row) throw new Error('target creation did not return a row'); return row
  }
  async findTarget(scope: AlertScope, id: string): Promise<NotificationTargetListRecord | null> { return (await this.database.query<NotificationTargetListRecord>(`SELECT id,type,label,enabled,verified_at,created_at,updated_at,disabled_at FROM notification_targets WHERE tenant_id=$1 AND project_id=$2 AND id=$3`, [ scope.tenantId, scope.projectId, id ])).rows[0] ?? null }
  async updateTarget(scope: AlertScope, id: string, actorId: string, patch: AlertTargetPatch): Promise<NotificationTargetListRecord | null> {
    const result = await this.database.query<{ id: string }>(`WITH updated AS (UPDATE notification_targets SET label=COALESCE($4,label), enabled=COALESCE($5,enabled), disabled_at=CASE WHEN COALESCE($5,enabled) THEN NULL ELSE COALESCE(disabled_at,now()) END, updated_at=GREATEST(date_trunc('milliseconds',now()),date_trunc('milliseconds',updated_at)+interval '1 millisecond') WHERE tenant_id=$1 AND project_id=$2 AND id=$3 AND date_trunc('milliseconds',updated_at)=$6 AND (COALESCE($5,enabled)=false OR verified_at IS NOT NULL) RETURNING id), audit AS (INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,metadata) SELECT $7,$1,$8,'notification_target_updated','notification_target',id,jsonb_build_object('enabled',$5 IS NOT NULL) FROM updated) SELECT id FROM updated`, [ scope.tenantId, scope.projectId, id, patch.label ?? null, patch.enabled ?? null, patch.expectedUpdatedAt, randomUUID(), actorId ]); return result.rows[0] ? this.findTarget(scope, id) : null
  }
  async disableTarget(scope: AlertScope, id: string, actorId: string, expected: Date): Promise<boolean> { const result = await this.database.query(`WITH updated AS (UPDATE notification_targets SET enabled=false,disabled_at=now(),updated_at=GREATEST(date_trunc('milliseconds',now()),date_trunc('milliseconds',updated_at)+interval '1 millisecond') WHERE tenant_id=$1 AND project_id=$2 AND id=$3 AND enabled AND date_trunc('milliseconds',updated_at)=$4 RETURNING id), audit AS (INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,metadata) SELECT $5,$1,$6,'notification_target_disabled','notification_target',id,'{}'::jsonb FROM updated) SELECT id FROM updated`, [ scope.tenantId, scope.projectId, id, expected, randomUUID(), actorId ]); return result.rowCount === 1 }
  async findRule(scope: AlertScope, id: string): Promise<AlertRuleListRecord | null> { return (await this.ruleRows('WHERE rule.tenant_id=$1 AND rule.project_id=$2 AND rule.id=$3', [ scope.tenantId, scope.projectId, id ]))[0] ?? null }
  async updateRule(scope: AlertScope, id: string, actorId: string, input: AlertRuleInput, expected: Date): Promise<AlertRuleListRecord | null> {
    const result = await this.database.query<{ id: string }>(`WITH valid_targets AS (SELECT id FROM notification_targets WHERE tenant_id=$1 AND project_id=$2 AND id=ANY($6::uuid[]) AND enabled AND verified_at IS NOT NULL AND disabled_at IS NULL), updated AS (UPDATE alert_rules SET name=$4,enabled=$5,condition_json=$7::jsonb,targets_version=targets_version+1,updated_at=GREATEST(date_trunc('milliseconds',now()),date_trunc('milliseconds',updated_at)+interval '1 millisecond') WHERE tenant_id=$1 AND project_id=$2 AND id=$3 AND date_trunc('milliseconds',updated_at)=$8 AND (SELECT count(*) FROM valid_targets)=cardinality($6::uuid[]) RETURNING id), wiped AS (DELETE FROM alert_rule_targets WHERE rule_id=$3 AND EXISTS(SELECT 1 FROM updated) RETURNING rule_id), linked AS (INSERT INTO alert_rule_targets (rule_id,target_id) SELECT $3,id FROM valid_targets WHERE EXISTS(SELECT 1 FROM updated)), audit AS (INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,metadata) SELECT $9,$1,$10,'alert_rule_updated','alert_rule',id,jsonb_build_object('target_count',cardinality($6::uuid[])) FROM updated) SELECT id FROM updated`, [ scope.tenantId, scope.projectId, id, input.name, input.enabled, input.targetIds, JSON.stringify(input.condition), expected, randomUUID(), actorId ]); return result.rows[0] ? this.findRule(scope, id) : null
  }
  async disableRule(scope: AlertScope, id: string, actorId: string, expected: Date): Promise<boolean> { const result = await this.database.query(`WITH updated AS (UPDATE alert_rules SET enabled=false,updated_at=GREATEST(date_trunc('milliseconds',now()),date_trunc('milliseconds',updated_at)+interval '1 millisecond') WHERE tenant_id=$1 AND project_id=$2 AND id=$3 AND enabled AND date_trunc('milliseconds',updated_at)=$4 RETURNING id), audit AS (INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,metadata) SELECT $5,$1,$6,'alert_rule_disabled','alert_rule',id,'{}'::jsonb FROM updated) SELECT id FROM updated`, [ scope.tenantId, scope.projectId, id, expected, randomUUID(), actorId ]); return result.rowCount === 1 }
  async listTargets(scope: AlertScope, query: AlertListQuery): Promise<NotificationTargetListRecord[]> { const values: unknown[]=[scope.tenantId,scope.projectId]; const clauses=['tenant_id=$1','project_id=$2']; if(query.cursor){values.push(query.cursor.createdAt,query.cursor.id);clauses.push(`(created_at,id)<($${values.length-1},$${values.length})`)} values.push(query.limit+1); return (await this.database.query<NotificationTargetListRecord>(`SELECT id,type,label,enabled,verified_at,created_at,updated_at,disabled_at FROM notification_targets WHERE ${clauses.join(' AND ')} ORDER BY created_at DESC,id DESC LIMIT $${values.length}`,values)).rows }
  async listRules(scope: AlertScope, query: AlertListQuery): Promise<AlertRuleListRecord[]> { const values:unknown[]=[scope.tenantId,scope.projectId]; const clauses=['rule.tenant_id=$1','rule.project_id=$2'];if(query.cursor){values.push(query.cursor.createdAt,query.cursor.id);clauses.push(`(rule.created_at,rule.id)<($${values.length-1},$${values.length})`)}values.push(query.limit+1);return this.ruleRows(`WHERE ${clauses.join(' AND ')} ORDER BY rule.created_at DESC,rule.id DESC LIMIT $${values.length}`,values) }
  async listInstances(scope: AlertScope, query: AlertListQuery): Promise<AlertInstanceListRecord[]> { const values:unknown[]=[scope.tenantId,scope.projectId];const clauses=['instance.tenant_id=$1','instance.project_id=$2'];if(query.cursor){values.push(query.cursor.createdAt,query.cursor.id);clauses.push(`(instance.first_triggered_at,instance.id)<($${values.length-1},$${values.length})`)}values.push(query.limit+1);return (await this.database.query<AlertInstanceListRecord>(`SELECT instance.id,instance.rule_id,rule.name AS rule_name,rule.rule_type,instance.group_key,instance.status,instance.first_triggered_at,instance.last_triggered_at,instance.last_evaluated_at,instance.cooldown_until,instance.payload_summary,instance.first_triggered_at AS created_at FROM alert_instances instance JOIN alert_rules rule ON rule.id=instance.rule_id AND rule.tenant_id=instance.tenant_id AND rule.project_id=instance.project_id WHERE ${clauses.join(' AND ')} ORDER BY instance.first_triggered_at DESC,instance.id DESC LIMIT $${values.length}`,values)).rows }
  async listDeliveries(scope: AlertScope, query: AlertListQuery): Promise<NotificationDeliveryListRecord[]> { const values:unknown[]=[scope.tenantId,scope.projectId];const clauses=['delivery.tenant_id=$1','delivery.project_id=$2'];if(query.cursor){values.push(query.cursor.createdAt,query.cursor.id);clauses.push(`(delivery.created_at,delivery.id)<($${values.length-1},$${values.length})`)}values.push(query.limit+1);return (await this.database.query<NotificationDeliveryListRecord>(`SELECT delivery.id,delivery.alert_instance_id,delivery.target_id,target.type AS target_type,target.label AS target_label,delivery.status,delivery.attempt_count,delivery.last_attempt_at,delivery.delivered_at,delivery.last_error_code,delivery.created_at FROM notification_deliveries delivery JOIN notification_targets target ON target.id=delivery.target_id AND target.tenant_id=delivery.tenant_id AND target.project_id=delivery.project_id WHERE ${clauses.join(' AND ')} ORDER BY delivery.created_at DESC,delivery.id DESC LIMIT $${values.length}`,values)).rows }
  async upsertAlertInstance(scope: AlertScope, ruleId: string, groupKey: string, cooldownUntil: Date, summary: SafeAlertSummary): Promise<{ id: string; enqueued: boolean }> { const result=await this.database.query<{id:string;created:boolean}>(`INSERT INTO alert_instances (id,tenant_id,project_id,rule_id,group_key,status,first_triggered_at,last_triggered_at,last_evaluated_at,cooldown_until,payload_summary) VALUES ($1,$2,$3,$4,$5,'active',now(),now(),now(),$6,$7::jsonb) ON CONFLICT(rule_id,group_key) DO UPDATE SET last_evaluated_at=now(),payload_summary=EXCLUDED.payload_summary,last_triggered_at=CASE WHEN alert_instances.cooldown_until<=now() THEN now() ELSE alert_instances.last_triggered_at END,cooldown_until=CASE WHEN alert_instances.cooldown_until<=now() THEN EXCLUDED.cooldown_until ELSE alert_instances.cooldown_until END RETURNING id,(xmax=0) AS created`,[randomUUID(),scope.tenantId,scope.projectId,ruleId,groupKey,cooldownUntil,JSON.stringify(summary)]);const row=result.rows[0];if(!row)throw new Error('alert instance did not return a row');return {id:row.id,enqueued:row.created} }
  async queueDelivery(scope: AlertScope, alertInstanceId: string, targetId: string): Promise<boolean> { const result=await this.database.query(`WITH delivery AS (INSERT INTO notification_deliveries (id,tenant_id,project_id,alert_instance_id,target_id) SELECT $1,$2,$3,$4,$5 WHERE EXISTS(SELECT 1 FROM alert_instances WHERE id=$4 AND tenant_id=$2 AND project_id=$3) AND EXISTS(SELECT 1 FROM notification_targets WHERE id=$5 AND tenant_id=$2 AND project_id=$3 AND enabled AND verified_at IS NOT NULL AND disabled_at IS NULL) ON CONFLICT (alert_instance_id, target_id, payload_version) DO NOTHING RETURNING id), outbox AS (INSERT INTO outbox_messages (id,tenant_id,project_id,topic,idempotency_key,payload,max_attempts) SELECT $6,$2,$3,'notification_delivery','notification-delivery:'||id,jsonb_build_object('notification_delivery_id',id),5 FROM delivery RETURNING id) SELECT id FROM outbox`,[randomUUID(),scope.tenantId,scope.projectId,alertInstanceId,targetId,randomUUID()]);return result.rowCount===1 }
  private async ruleRows(suffix:string,values:readonly unknown[]):Promise<AlertRuleListRecord[]> { return (await this.database.query<AlertRuleListRecord>(`SELECT rule.id,rule.name,rule.enabled,rule.rule_type,rule.condition_json,rule.targets_version,COALESCE(array_agg(link.target_id ORDER BY link.target_id) FILTER (WHERE link.target_id IS NOT NULL),'{}'::uuid[]) AS target_ids,rule.created_at,rule.updated_at FROM alert_rules rule LEFT JOIN alert_rule_targets link ON link.rule_id=rule.id ${suffix.includes('ORDER BY') ? suffix.replace(' ORDER BY', ' GROUP BY rule.id ORDER BY') : `${suffix} GROUP BY rule.id`}`,values)).rows }
}
