import assert from 'node:assert/strict'
import { describe, it } from 'mocha'
import { SsoFacade } from '../../../../app/service/sso'
import { OidcVerifier, SsoConnection, SsoRepository, SsoTransaction, VerifiedOidcIdentity } from '../../../../app/service/sso/types'
const conn: SsoConnection={id:'00000000-0000-4000-8000-000000000010',tenantId:'00000000-0000-4000-8000-000000000001',issuer:'https://issuer.example',clientId:'client',clientSecretEncrypted:Buffer.from('x'.repeat(28)),allowedEmailDomains:['example.com'],defaultRole:'member',enabled:true}
class MemoryRepo implements SsoRepository { tx: { stateHash:Buffer; txn:SsoTransaction; used:boolean }|null=null; identities=new Map<string,string>(); async list(){return[conn]} async get(_t:string,id:string){return id===conn.id?conn:null} async create(i:Omit<SsoConnection,'id'>&{id:string}){return {...i,id:i.id}} async update(){return conn} async createTransaction(i:{id:string;connectionId:string;stateHash:Buffer;nonce:string;pkceVerifierEncrypted:Buffer;redirectUri:string}){this.tx={stateHash:i.stateHash,used:false,txn:{id:i.id,connection:conn,nonce:i.nonce,pkceVerifierEncrypted:i.pkceVerifierEncrypted,redirectUri:i.redirectUri}}} async consumeTransaction(state:Buffer){if(!this.tx||this.tx.used||!this.tx.stateHash.equals(state))return null;this.tx.used=true;return this.tx.txn} async linkVerifiedIdentity(i:{transaction:SsoTransaction;identity:VerifiedOidcIdentity}){return this.identities.get(i.identity.subject)??null} async createExplicitIdentity(i:{subject:string;userId:string}){if(this.identities.has(i.subject))return false;this.identities.set(i.subject,i.userId);return true} }
const verifier:OidcVerifier={async discover(){return{issuer:'https://issuer.example',authorizationEndpoint:'https://issuer.example/auth',tokenEndpoint:'https://issuer.example/token',jwksUri:'https://issuer.example/jwks'}},async exchangeAndVerify(i){return{issuer:i.connection.issuer,audience:i.connection.clientId,subject:'subject-a',email:'member@example.com',emailVerified:true,nonce:i.nonce}}}
function facade(repo=new MemoryRepo(),v:OidcVerifier|null=verifier){return {repo,facade:new SsoFacade({repository:repo,verifier:v??undefined,appOrigin:'https://app.example',seal:x=>Buffer.from(x),unseal:x=>x.toString(),createId:()=> '00000000-0000-4000-8000-000000000099',random:n=>'a'.repeat(n+12),now:()=>new Date('2026-01-01T00:00:00Z')})}}
const owner={tenantId:conn.tenantId,userId:'00000000-0000-4000-8000-000000000002',role:'owner' as const}
describe('OIDC SSO',()=>{
 it('uses PKCE, nonce and single-use state before a known identity can sign in',async()=>{const {repo,facade:f}=facade();repo.identities.set('subject-a','00000000-0000-4000-8000-000000000003');const started=await f.start(conn.tenantId,conn.id);const url=new URL(started.authorization_url);assert.equal(url.searchParams.get('code_challenge_method'),'S256');assert.ok(url.searchParams.get('state'));assert.equal(repo.tx?.txn.nonce.length,44);const complete=await f.callback({state:url.searchParams.get('state'),code:'code'});assert.equal(complete.user_id,'00000000-0000-4000-8000-000000000003');await assert.rejects(()=>f.callback({state:url.searchParams.get('state'),code:'code'}),{code:'sso_callback_failed'}) })
 it('fails closed without an installed OIDC verifier',async()=>{const {facade:f}=facade(new MemoryRepo(),null);await assert.rejects(()=>f.start(conn.tenantId,conn.id),{code:'sso_unavailable'})})
 it('does not merge a verified email unless an owner explicitly links the issuer subject',async()=>{const {repo,facade:f}=facade();const started=await f.start(conn.tenantId,conn.id);const state=new URL(started.authorization_url).searchParams.get('state');await assert.rejects(()=>f.callback({state,code:'code'}),{code:'sso_identity_link_required'});await f.link(owner,conn.id,{subject:'subject-a',email:'member@example.com',user_id:'00000000-0000-4000-8000-000000000004'});const again=await f.start(conn.tenantId,conn.id);const state2=new URL(again.authorization_url).searchParams.get('state');assert.equal((await f.callback({state:state2,code:'code'})).user_id,'00000000-0000-4000-8000-000000000004');assert.equal(repo.identities.size,1)})
 it('restricts connection management and identity linking to owners',async()=>{const {facade:f}=facade();await assert.rejects(()=>f.list({...owner,role:'admin'}),{code:'tenant_action_denied'});await assert.rejects(()=>f.link(owner,conn.id,{subject:'x',email:'outside.test',user_id:'00000000-0000-4000-8000-000000000004'}),{code:'invalid_sso_connection'})})
})
