import { createHash, randomBytes, randomUUID } from 'node:crypto'
import { Service } from 'egg'
import { httpError } from '../../lib/http'
import { normalizeEmail } from '../auth'
import { isUuid, parseRole } from '../tenancy'
import { SsoConnection, SsoDependencies } from './types'
const TTL=10*60*1000
export class SsoFacade {
 constructor(private readonly deps:SsoDependencies) {}
 async list(scope:Scope){this.owner(scope); return {connections:(await this.deps.repository.list(scope.tenantId)).map(dto)}}
 async create(scope:Scope,raw:unknown,requestId?:string){this.owner(scope); const v=obj(raw); const issuer=issuerOf(v.issuer); const clientId=text(v.client_id,1,1024); const secret=text(v.client_secret,1,4096); const defaultRole=role(v.default_role); const domains=domainsOf(v.allowed_email_domains); if(!issuer||!clientId||!secret||!defaultRole||!domains) throw invalid(); const row=await this.deps.repository.create({id:this.id(),tenantId:scope.tenantId,issuer,clientId,clientSecretEncrypted:this.deps.seal(secret),allowedEmailDomains:domains,defaultRole,enabled:v.enabled===true,actorUserId:scope.userId,requestId}); return {connection:dto(row)} }
 async update(scope:Scope,id:unknown,raw:unknown,requestId?:string){this.owner(scope); if(!isUuid(id))throw missing(); const v=obj(raw); const patch: {clientId?:string;clientSecretEncrypted?:Buffer;allowedEmailDomains?:string[];defaultRole?:SsoConnection['defaultRole'];enabled?:boolean}={}; if(v.client_id!==undefined){const x=text(v.client_id,1,1024);if(!x)throw invalid();patch.clientId=x} if(v.client_secret!==undefined){const x=text(v.client_secret,1,4096);if(!x)throw invalid();patch.clientSecretEncrypted=this.deps.seal(x)} if(v.allowed_email_domains!==undefined){const x=domainsOf(v.allowed_email_domains);if(!x)throw invalid();patch.allowedEmailDomains=x} if(v.default_role!==undefined){const x=role(v.default_role);if(!x)throw invalid();patch.defaultRole=x} if(v.enabled!==undefined){if(typeof v.enabled!=='boolean')throw invalid();patch.enabled=v.enabled} if(Object.keys(patch).length===0)throw invalid(); const row=await this.deps.repository.update({tenantId:scope.tenantId,id,actorUserId:scope.userId,patch,requestId});if(!row)throw missing();return {connection:dto(row)} }
 async link(scope:Scope,connectionId:unknown,raw:unknown,requestId?:string){this.owner(scope);if(!isUuid(connectionId))throw missing();const c=await this.deps.repository.get(scope.tenantId,connectionId);const v=obj(raw);const subject=text(v.subject,1,1024),email=normalizeEmail(v.email);if(!c||!subject||!email||!isUuid(v.user_id))throw invalid();if(!allowed(email,c.allowedEmailDomains))throw invalid();const linked=await this.deps.repository.createExplicitIdentity({tenantId:scope.tenantId,issuer:c.issuer,subject,userId:v.user_id,email,actorUserId:scope.userId,requestId});if(!linked)throw httpError(409,'sso_identity_link_failed','SSO identity could not be linked');return {linked:true} }
 async start(tenantId:unknown,connectionId:unknown){if(!isUuid(tenantId)||!isUuid(connectionId))throw startFailed(); const connection=await this.deps.repository.get(tenantId,connectionId); const verifier=this.deps.verifier;if(!connection||!connection.enabled||!verifier)throw httpError(503,'sso_unavailable','Single sign-on is unavailable'); const discovery=await verifier.discover(connection.issuer);if(!validDiscovery(discovery,connection.issuer))throw httpError(503,'sso_unavailable','Single sign-on is unavailable'); const state=this.secret(32),nonce=this.secret(32),verifierCode=this.secret(48); const redirectUri=`${this.deps.appOrigin.replace(/\/$/,'')}/api/sso/callback`; await this.deps.repository.createTransaction({id:this.id(),connectionId:connection.id,stateHash:hash(state),nonce,pkceVerifierEncrypted:this.deps.seal(verifierCode),redirectUri,expiresAt:new Date(this.now().getTime()+TTL)}); const u=new URL(discovery.authorizationEndpoint);u.searchParams.set('response_type','code');u.searchParams.set('client_id',connection.clientId);u.searchParams.set('redirect_uri',redirectUri);u.searchParams.set('scope','openid email');u.searchParams.set('state',state);u.searchParams.set('nonce',nonce);u.searchParams.set('code_challenge',base64url(createHash('sha256').update(verifierCode).digest()));u.searchParams.set('code_challenge_method','S256');return {authorization_url:u.toString()} }
 async callback(raw:unknown,requestId?:string){const v=obj(raw);const state=text(v.state,32,2048),code=text(v.code,1,8192);if(!state||!code)throw callbackFailed();const txn=await this.deps.repository.consumeTransaction(hash(state),this.now());if(!txn)throw callbackFailed();const verifier=this.deps.verifier;if(!verifier)throw callbackFailed();let discovery;try{discovery=await verifier.discover(txn.connection.issuer)}catch{throw callbackFailed()}if(!validDiscovery(discovery,txn.connection.issuer))throw callbackFailed();let identity;try{identity=await verifier.exchangeAndVerify({connection:txn.connection,discovery,code,redirectUri:txn.redirectUri,pkceVerifier:this.deps.unseal(txn.pkceVerifierEncrypted),nonce:txn.nonce})}catch{throw callbackFailed()}if(!identity||identity.issuer!==txn.connection.issuer||identity.audience!==txn.connection.clientId||identity.nonce!==txn.nonce||!identity.emailVerified||!validSubject(identity.subject))throw callbackFailed();const email=normalizeEmail(identity.email);if(!email||!allowed(email,txn.connection.allowedEmailDomains))throw callbackFailed();const userId=await this.deps.repository.linkVerifiedIdentity({transaction:txn,identity:{...identity,email},now:this.now(),requestId}); if(!userId) throw httpError(403,'sso_identity_link_required','Single sign-on identity must be linked by an authenticated administrator');return {user_id:userId} }
 private owner(scope:Scope){if(scope.role!=='owner')throw httpError(403,'tenant_action_denied','Tenant action is denied')};private now(){return(this.deps.now??(()=>new Date()))()};private id(){return(this.deps.createId??randomUUID)()};private secret(bytes:number){return(this.deps.random??(n=>randomBytes(n).toString('base64url')))(bytes)}
}
type Scope={tenantId:string;userId:string;role:import('../database/types').MembershipRole}
export function ssoDependenciesFromApp(app:unknown):SsoDependencies|null{return(app as {ssoDependencies?:SsoDependencies}).ssoDependencies??null}
export default class SsoService extends Service { private domain(){const d=ssoDependenciesFromApp(this.app);if(!d)throw httpError(503,'sso_unavailable','Single sign-on is unavailable');return new SsoFacade(d)} list(s:Scope){return this.domain().list(s)} create(s:Scope,r:unknown,id?:string){return this.domain().create(s,r,id)} update(s:Scope,i:unknown,r:unknown,id?:string){return this.domain().update(s,i,r,id)} link(s:Scope,i:unknown,r:unknown,id?:string){return this.domain().link(s,i,r,id)} start(t:unknown,i:unknown){return this.domain().start(t,i)} callback(r:unknown,id?:string){return this.domain().callback(r,id)} }
function dto(c:SsoConnection){return{id:c.id,issuer:c.issuer,client_id:c.clientId,allowed_email_domains:c.allowedEmailDomains,default_role:c.defaultRole,enabled:c.enabled}}
function obj(x:unknown){if(!x||typeof x!=='object'||Array.isArray(x))throw invalid();return x as Record<string,unknown>};function text(x:unknown,min:number,max:number){return typeof x==='string'&&x.trim()===x&&x.length>=min&&x.length<=max?x:null};function issuerOf(x:unknown){const s=text(x,8,2048);if(!s)return null;try{const u=new URL(s);return u.protocol==='https:'&&u.username===''&&u.password===''&&u.hash===''&&u.search===''&&u.pathname==='/'?u.toString().replace(/\/$/,''):null}catch{return null}};function domainsOf(x:unknown){if(!Array.isArray(x)||x.length>50)return null;const out:string[]=[];for(const y of x){if(typeof y!=='string'||!/^([a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(y.trim().toLowerCase()))return null;const d=y.trim().toLowerCase();if(!out.includes(d))out.push(d)}return out};function role(x:unknown){const r=parseRole(x);return r&&r!=='owner'?r:null};function validDiscovery(d:import('./types').OidcDiscovery|null,issuer:string):d is import('./types').OidcDiscovery{return!!d&&d.issuer===issuer&&https(d.authorizationEndpoint)&&https(d.tokenEndpoint)&&https(d.jwksUri)};function https(x:string){try{return new URL(x).protocol==='https:'}catch{return false}};function hash(x:string){return createHash('sha256').update(x).digest()};function base64url(v:Buffer){return v.toString('base64url')};function validSubject(x:unknown){return typeof x==='string'&&x.length>0&&x.length<=1024};function allowed(email:string,domains:string[]){return domains.length===0||domains.includes(email.slice(email.lastIndexOf('@')+1))};function invalid(){return httpError(400,'invalid_sso_connection','SSO connection is invalid')};function missing(){return httpError(404,'sso_connection_not_found','SSO connection was not found')};function startFailed(){return httpError(400,'sso_start_failed','Single sign-on could not be started')};function callbackFailed(){return httpError(400,'sso_callback_failed','Single sign-on sign-in failed')}
