import { randomUUID } from 'node:crypto'
import { SsoConnection, SsoDatabaseDependencies, SsoRepository, SsoTransaction, VerifiedOidcIdentity } from './types'
type Row = { id:string; tenant_id:string; issuer:string; client_id:string; client_secret_encrypted:Buffer; allowed_email_domains:string[]; default_role:SsoConnection['defaultRole']; enabled:boolean }
const select = 'id, tenant_id, issuer, client_id, client_secret_encrypted, allowed_email_domains, default_role, enabled'
function connection(row: Row): SsoConnection { return { id:row.id, tenantId:row.tenant_id, issuer:row.issuer, clientId:row.client_id, clientSecretEncrypted:row.client_secret_encrypted, allowedEmailDomains:row.allowed_email_domains, defaultRole:row.default_role, enabled:row.enabled } }
export class PostgresSsoRepository implements SsoRepository {
 constructor(private readonly deps:SsoDatabaseDependencies) {}
 async list(tenantId:string) { const r=await this.deps.database.query<Row>(`SELECT ${select} FROM sso_connections WHERE tenant_id=$1 ORDER BY created_at ASC`,[tenantId]); return r.rows.map(connection) }
 async get(tenantId:string,id:string) { const r=await this.deps.database.query<Row>(`SELECT ${select} FROM sso_connections WHERE tenant_id=$1 AND id=$2`,[tenantId,id]); return r.rows[0] ? connection(r.rows[0]) : null }
 async create(input: Omit<SsoConnection,'id'> & {id:string;actorUserId:string;requestId?:string}) { return this.deps.database.transaction(async tx=>{ const r=await tx.query<Row>(`INSERT INTO sso_connections (${select},created_by_user_id,updated_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING ${select}`,[input.id,input.tenantId,input.issuer,input.clientId,input.clientSecretEncrypted,input.allowedEmailDomains,input.defaultRole,input.enabled,input.actorUserId,input.actorUserId]); const row=r.rows[0]; if(!row) throw new Error('SSO connection did not persist'); await audit(tx,input.tenantId,input.actorUserId,'sso_connection_created',input.id,{},input.requestId); return connection(row) }) }
 async update(input: {tenantId:string;id:string;actorUserId:string;patch:Partial<Pick<SsoConnection,'clientId'|'clientSecretEncrypted'|'allowedEmailDomains'|'defaultRole'|'enabled'>>;requestId?:string}) { return this.deps.database.transaction(async tx=>{ const r=await tx.query<Row>(`UPDATE sso_connections SET client_id=COALESCE($3,client_id),client_secret_encrypted=COALESCE($4,client_secret_encrypted),allowed_email_domains=COALESCE($5,allowed_email_domains),default_role=COALESCE($6,default_role),enabled=COALESCE($7,enabled),updated_by_user_id=$8,updated_at=now() WHERE tenant_id=$1 AND id=$2 RETURNING ${select}`,[input.tenantId,input.id,input.patch.clientId??null,input.patch.clientSecretEncrypted??null,input.patch.allowedEmailDomains??null,input.patch.defaultRole??null,input.patch.enabled??null,input.actorUserId]); const row=r.rows[0]; if(!row)return null; await audit(tx,input.tenantId,input.actorUserId,'sso_connection_updated',input.id,{enabled:row.enabled},input.requestId); return connection(row) }) }
 async createTransaction(input:{id:string;connectionId:string;stateHash:Buffer;nonce:string;pkceVerifierEncrypted:Buffer;redirectUri:string;expiresAt:Date}) { await this.deps.database.query(`INSERT INTO sso_authorization_transactions (id,connection_id,state_hash,nonce,pkce_verifier_encrypted,redirect_uri,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7)`,[input.id,input.connectionId,input.stateHash,input.nonce,input.pkceVerifierEncrypted,input.redirectUri,input.expiresAt]) }
 async consumeTransaction(stateHash:Buffer,now:Date):Promise<SsoTransaction|null> { return this.deps.database.transaction(async tx=>{ const r=await tx.query<Row & {transaction_id:string;nonce:string;pkce_verifier_encrypted:Buffer;redirect_uri:string}>(`SELECT t.id AS transaction_id,t.nonce,t.pkce_verifier_encrypted,t.redirect_uri,${select.split(', ').map(v=>'c.'+v).join(', ')} FROM sso_authorization_transactions t JOIN sso_connections c ON c.id=t.connection_id WHERE t.state_hash=$1 AND t.consumed_at IS NULL AND t.expires_at>$2 AND c.enabled=true FOR UPDATE`,[stateHash,now]); const row=r.rows[0]; if(!row)return null; const u=await tx.query('UPDATE sso_authorization_transactions SET consumed_at=$2 WHERE id=$1 AND consumed_at IS NULL',[row.transaction_id,now]); if(u.rowCount!==1)return null; return {id:row.transaction_id,connection:connection(row),nonce:row.nonce,pkceVerifierEncrypted:row.pkce_verifier_encrypted,redirectUri:row.redirect_uri} }) }
 async createExplicitIdentity(input:{tenantId:string;issuer:string;subject:string;userId:string;email:string;actorUserId:string;requestId?:string}) { return this.deps.database.transaction(async tx=>{ const user=await tx.query<{id:string}>(`SELECT u.id FROM users u JOIN memberships m ON m.user_id=u.id AND m.tenant_id=$3 WHERE u.id=$1 AND u.email_normalized=$2 FOR UPDATE`,[input.userId,input.email,input.tenantId]); if(!user.rows[0]) return false; const inserted=await tx.query(`INSERT INTO sso_identities (tenant_id,issuer,subject,user_id,email_normalized) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (tenant_id,issuer,subject) DO NOTHING`,[input.tenantId,input.issuer,input.subject,input.userId,input.email]); if(inserted.rowCount!==1)return false; await audit(tx,input.tenantId,input.actorUserId,'sso_identity_linked',input.subject,{user_id:input.userId},input.requestId);return true }) }
 async linkVerifiedIdentity(input:{transaction:SsoTransaction;identity:VerifiedOidcIdentity;now:Date;requestId?:string}) { return this.deps.database.transaction(async tx=>{ const found=await tx.query<{user_id:string}>(`SELECT user_id FROM sso_identities WHERE tenant_id=$1 AND issuer=$2 AND subject=$3 FOR UPDATE`,[input.transaction.connection.tenantId,input.identity.issuer,input.identity.subject]); const existing=found.rows[0]; if(!existing) return null; await tx.query('UPDATE sso_identities SET email_normalized=$5,updated_at=$4 WHERE tenant_id=$1 AND issuer=$2 AND subject=$3',[input.transaction.connection.tenantId,input.identity.issuer,input.identity.subject,input.now,input.identity.email]); await audit(tx,input.transaction.connection.tenantId,existing.user_id,'sso_login',input.transaction.connection.id,{},input.requestId); return existing.user_id }) }
}
async function audit(tx: import('../database/types').DatabaseTransaction,tenantId:string,actor:string,action:string,target:string,metadata:Record<string,unknown>,requestId?:string){await tx.query(`INSERT INTO audit_logs (id,tenant_id,actor_user_id,action,target_type,target_id,request_id,metadata) VALUES ($1,$2,$3,$4,'sso_connection',$5,$6,$7::jsonb)`,[randomUUID(),tenantId,actor,action,target,requestId??null,JSON.stringify(metadata)])}
