import { MembershipRole, DatabasePool } from '../database/types'
export type SsoRole = Exclude<MembershipRole, 'owner'>
export interface SsoConnection { id: string; tenantId: string; issuer: string; clientId: string; clientSecretEncrypted: Buffer; allowedEmailDomains: string[]; defaultRole: SsoRole; enabled: boolean }
export interface SsoTransaction { id: string; connection: SsoConnection; nonce: string; pkceVerifierEncrypted: Buffer; redirectUri: string }
export interface OidcDiscovery { issuer: string; authorizationEndpoint: string; tokenEndpoint: string; jwksUri: string }
export interface VerifiedOidcIdentity { issuer: string; audience: string; subject: string; email: string; emailVerified: boolean; nonce: string }
export interface OidcVerifier { discover(issuer: string): Promise<OidcDiscovery | null>; exchangeAndVerify(input: { connection: SsoConnection; discovery: OidcDiscovery; code: string; redirectUri: string; pkceVerifier: string; nonce: string }): Promise<VerifiedOidcIdentity | null> }
export interface SsoRepository { list(tenantId: string): Promise<SsoConnection[]>; get(tenantId: string, id: string): Promise<SsoConnection | null>; create(input: Omit<SsoConnection, 'id'> & { id: string; actorUserId: string; requestId?: string }): Promise<SsoConnection>; update(input: { tenantId: string; id: string; actorUserId: string; patch: Partial<Pick<SsoConnection, 'clientId'|'clientSecretEncrypted'|'allowedEmailDomains'|'defaultRole'|'enabled'>>; requestId?: string }): Promise<SsoConnection | null>; createTransaction(input: { id: string; connectionId: string; stateHash: Buffer; nonce: string; pkceVerifierEncrypted: Buffer; redirectUri: string; expiresAt: Date }): Promise<void>; consumeTransaction(stateHash: Buffer, now: Date): Promise<SsoTransaction | null>; linkVerifiedIdentity(input: { transaction: SsoTransaction; identity: VerifiedOidcIdentity; now: Date; requestId?: string }): Promise<string | null>; createExplicitIdentity(input: { tenantId: string; issuer: string; subject: string; userId: string; email: string; actorUserId: string; requestId?: string }): Promise<boolean> }
export interface SsoDependencies { repository: SsoRepository; verifier?: OidcVerifier; seal(value: string): Buffer; unseal(value: Buffer): string; now?: () => Date; createId?: () => string; random?: (bytes: number) => string; appOrigin: string }
export interface SsoDatabaseDependencies { database: DatabasePool; seal(value: string): Buffer; unseal(value: Buffer): string }
