import { Application } from 'egg'
import authCsrf from './middleware/authCsrf'
import authOrigin from './middleware/authOrigin'
import authSession from './middleware/authSession'
import projectAccess from './middleware/projectAccess'

export default (app: Application) => {
  const { controller, router } = app
  const session = authSession()
  const write = [ session, authOrigin(), authCsrf() ] as const
  const project = projectAccess()
  const projectRead = [ session, project ] as const
  const projectWrite = [ session, project, authOrigin(), authCsrf() ] as const

  router.get('/health/live', controller.health.live)
  router.get('/health/ready', controller.health.ready)
  router.get('/health/metrics', controller.runtimeMetrics.show)
  router.options('/api/sdk/config', controller.sdkConfig.preflight)
  router.get('/api/sdk/config', controller.sdkConfig.show)

  router.options('/api/ingest/events', controller.ingest.preflight)
  router.post('/api/ingest/events', controller.ingest.events)
  router.options('/api/ingest/errors', controller.ingest.preflight)
  router.post('/api/ingest/errors', controller.ingest.errors)
  router.options('/api/ingest/behavior', controller.ingest.preflight)
  router.post('/api/ingest/behavior', controller.ingest.behavior)
  router.options('/api/ingest/replays', controller.ingest.preflight)
  router.post('/api/ingest/replays', controller.ingest.replays)
  router.options('/api/ingest/performance', controller.ingest.preflight)
  router.post('/api/ingest/performance', controller.ingest.performance)
  router.post('/api/ingest/server/events', controller.ingestServer.events)
  router.post('/api/ingest/server/errors', controller.ingestServer.errors)
  router.post('/api/ingest/server/identities', controller.identityDirectory.upsert)
  router.post('/api/identity/assertions', controller.identityAssertions.create)
  router.post('/api/ingest/mobile/events', controller.ingestMobile.events)
  router.post('/api/ingest/mobile/errors', controller.ingestMobile.errors)
  router.post('/api/otlp/v1/traces', controller.otlp.traces)
  router.post('/api/otlp/v1/metrics', controller.otlp.metrics)
  router.post('/api/otlp/v1/logs', controller.otlp.logs)

  router.post('/api/sourcemaps/upload', controller.sourcemaps.upload)
  router.get('/api/tenants/:tenantId/projects/:projectId/sourcemaps', ...projectRead, controller.sourcemapManagement.index)

  router.post('/api/auth/register', controller.auth.register)
  router.post('/api/auth/login', controller.auth.login)
  router.post('/api/auth/logout', ...write, controller.auth.logout)
  router.get('/api/auth/me', session, controller.auth.me)
  router.get('/api/me', session, controller.auth.me)
  router.get('/api/tenants', session, controller.auth.tenants)
  router.get('/api/sso/callback', controller.sso.callback)
  router.get('/api/tenants/:tenantId/sso/connections', session, controller.sso.list)
  router.post('/api/tenants/:tenantId/sso/connections', ...write, controller.sso.create)
  router.patch('/api/tenants/:tenantId/sso/connections/:connectionId', ...write, controller.sso.update)
  router.post('/api/tenants/:tenantId/sso/connections/:connectionId/identities', ...write, controller.sso.link)
  router.get('/api/tenants/:tenantId/sso/connections/:connectionId/start', controller.sso.start)

  router.post('/api/invitations/accept', controller.invitations.accept)
  router.post('/api/tenants/:tenantId/invitations', ...write, controller.invitations.create)
  router.post('/api/tenants/:tenantId/invitations/:invitationId/resend', ...write, controller.invitations.resend)

  router.get('/api/tenants/:tenantId/members', session, controller.tenants.members)
  router.post('/api/tenants/:tenantId/members', ...write, controller.tenants.addMember)
  router.post('/api/tenants/:tenantId/members/direct', ...write, controller.tenants.createMemberAccount)
  router.patch('/api/tenants/:tenantId/members/:userId', ...write, controller.tenants.updateMember)
  router.delete('/api/tenants/:tenantId/members/:userId', ...write, controller.tenants.removeMember)
  router.put('/api/tenants/:tenantId/members/:userId/projects', ...write, controller.tenants.updateMemberProjects)
  router.get('/api/tenants/:tenantId/settings', session, controller.tenants.defaults)
  router.patch('/api/tenants/:tenantId/settings', ...write, controller.tenants.updateDefaults)
  router.get('/api/tenants/:tenantId/audit-logs', session, controller.auditLogs.index)
  router.get('/api/tenants/:tenantId/usage', session, controller.usage.tenantSummary)
  router.patch('/api/tenants/:tenantId/subscription', ...write, controller.usage.configureSubscription)
  router.post('/api/tenants/:tenantId/usage-adjustments', ...write, controller.usage.adjust)

  router.get('/api/tenants/:tenantId/projects', session, controller.projects.index)
  router.post('/api/tenants/:tenantId/projects', ...write, controller.projects.create)
  router.patch('/api/tenants/:tenantId/projects/:projectId', ...projectWrite, controller.projects.update)
  router.get('/api/tenants/:tenantId/projects/:projectId/keys', ...projectRead, controller.projects.listKeys)
  router.post('/api/tenants/:tenantId/projects/:projectId/keys', ...projectWrite, controller.projects.createKey)
  router.post('/api/tenants/:tenantId/projects/:projectId/keys/:keyId/rotate', ...projectWrite, controller.projects.rotateKey)
  router.delete('/api/tenants/:tenantId/projects/:projectId/keys/:keyId', ...projectWrite, controller.projects.disableKey)

  router.get('/api/tenants/:tenantId/projects/:projectId/errors', ...projectRead, controller.errors.index)
  router.get('/api/tenants/:tenantId/projects/:projectId/errors/:groupId', ...projectRead, controller.errors.show)
  router.get('/api/tenants/:tenantId/projects/:projectId/errors/:groupId/occurrences', ...projectRead, controller.errors.occurrences)
  router.patch('/api/tenants/:tenantId/projects/:projectId/errors/:groupId/status', ...projectWrite, controller.errors.patchStatus)
  router.get('/api/tenants/:tenantId/projects/:projectId/analytics/trend', ...projectRead, controller.analytics.trend)
  router.get('/api/tenants/:tenantId/projects/:projectId/dashboard', ...projectRead, controller.analytics.dashboard)
  router.get('/api/tenants/:tenantId/projects/:projectId/events', ...projectRead, controller.analytics.events)
  router.get('/api/tenants/:tenantId/projects/:projectId/usage', ...projectRead, controller.usage.show)
  router.get('/api/tenants/:tenantId/projects/:projectId/funnel', ...projectRead, controller.funnel.show)
  router.get('/api/tenants/:tenantId/projects/:projectId/analytics/retention', ...projectRead, controller.advancedAnalytics.retention)
  router.get('/api/tenants/:tenantId/projects/:projectId/analytics/path', ...projectRead, controller.advancedAnalytics.path)
  router.get('/api/tenants/:tenantId/projects/:projectId/people', ...projectRead, controller.userJourneys.index)
  router.get('/api/tenants/:tenantId/projects/:projectId/people/:businessUserId/journey', ...projectRead, controller.userJourneys.show)
  router.get('/api/tenants/:tenantId/projects/:projectId/performance/pages/:pageKey', ...projectRead, controller.reporting.performanceDetail)
  router.get('/api/tenants/:tenantId/projects/:projectId/cohorts', ...projectRead, controller.cohorts.list)
  router.post('/api/tenants/:tenantId/projects/:projectId/cohorts', ...projectWrite, controller.cohorts.create)
  router.get('/api/tenants/:tenantId/projects/:projectId/cohorts/:cohortId', ...projectRead, controller.cohorts.show)
  router.patch('/api/tenants/:tenantId/projects/:projectId/cohorts/:cohortId', ...projectWrite, controller.cohorts.update)
  router.delete('/api/tenants/:tenantId/projects/:projectId/cohorts/:cohortId', ...projectWrite, controller.cohorts.destroy)
  router.post('/api/tenants/:tenantId/projects/:projectId/cohorts/:cohortId/preview', ...projectWrite, controller.cohorts.preview)
  router.get('/api/tenants/:tenantId/projects/:projectId/heatmaps', ...projectRead, controller.heatmaps.list)
  router.get('/api/tenants/:tenantId/projects/:projectId/heatmaps/:heatmapId', ...projectRead, controller.heatmaps.detail)
  router.get('/api/tenants/:tenantId/projects/:projectId/replays', ...projectRead, controller.replay.index)
  router.get('/api/tenants/:tenantId/projects/:projectId/replays/:replaySessionId', ...projectRead, controller.replay.show)
  router.get('/api/tenants/:tenantId/projects/:projectId/replays/:replaySessionId/chunks', ...projectRead, controller.replay.chunks)
  router.get('/api/tenants/:tenantId/projects/:projectId/alerts/targets', ...projectRead, controller.alerts.listTargets)
  router.get('/api/tenants/:tenantId/projects/:projectId/alerts/rules', ...projectRead, controller.alerts.listRules)
  router.get('/api/tenants/:tenantId/projects/:projectId/alerts/instances', ...projectRead, controller.alerts.listInstances)
  router.get('/api/tenants/:tenantId/projects/:projectId/alerts/deliveries', ...projectRead, controller.alerts.listDeliveries)
  router.post('/api/tenants/:tenantId/projects/:projectId/alerts/targets', ...projectWrite, controller.alerts.createTarget)
  router.post('/api/tenants/:tenantId/projects/:projectId/alerts/rules', ...projectWrite, controller.alerts.createRule)
  router.patch('/api/tenants/:tenantId/projects/:projectId/alerts/targets/:targetId', ...projectWrite, controller.alerts.updateTarget)
  router.delete('/api/tenants/:tenantId/projects/:projectId/alerts/targets/:targetId', ...projectWrite, controller.alerts.disableTarget)
  router.patch('/api/tenants/:tenantId/projects/:projectId/alerts/rules/:ruleId', ...projectWrite, controller.alerts.updateRule)
  router.delete('/api/tenants/:tenantId/projects/:projectId/alerts/rules/:ruleId', ...projectWrite, controller.alerts.disableRule)
  router.get('/api/tenants/:tenantId/projects/:projectId/insights', ...projectRead, controller.insights.list)
  router.post('/api/tenants/:tenantId/projects/:projectId/insights', ...projectWrite, controller.insights.create)
  router.get('/api/tenants/:tenantId/projects/:projectId/insights/:insightId', ...projectRead, controller.insights.show)
  router.patch('/api/tenants/:tenantId/projects/:projectId/insights/:insightId', ...projectWrite, controller.insights.update)
  router.delete('/api/tenants/:tenantId/projects/:projectId/insights/:insightId', ...projectWrite, controller.insights.destroy)
  router.get('/api/tenants/:tenantId/projects/:projectId/dashboards', ...projectRead, controller.insights.listDashboards)
  router.post('/api/tenants/:tenantId/projects/:projectId/dashboards', ...projectWrite, controller.insights.createDashboard)
  router.get('/api/tenants/:tenantId/projects/:projectId/dashboards/:dashboardId', ...projectRead, controller.insights.showDashboard)
  router.patch('/api/tenants/:tenantId/projects/:projectId/dashboards/:dashboardId', ...projectWrite, controller.insights.updateDashboard)
  router.delete('/api/tenants/:tenantId/projects/:projectId/dashboards/:dashboardId', ...projectWrite, controller.insights.destroyDashboard)
  router.put('/api/tenants/:tenantId/projects/:projectId/dashboards/:dashboardId/tiles', ...projectWrite, controller.insights.replaceTiles)
  router.get('/api/tenants/:tenantId/projects/:projectId/performance', ...projectRead, controller.reporting.performance)
  router.post('/api/tenants/:tenantId/projects/:projectId/analytics-exports', ...projectWrite, controller.reporting.createExport)
  router.post('/api/tenants/:tenantId/projects/:projectId/exports', ...projectWrite, controller.reporting.createExport)
  router.get('/api/tenants/:tenantId/projects/:projectId/analytics-exports/:exportJobId', ...projectRead, controller.reporting.showExport)
  router.post('/api/tenants/:tenantId/projects/:projectId/analytics-exports/:exportJobId/cancel', ...projectWrite, controller.reporting.cancelExport)
  router.get('/api/tenants/:tenantId/projects/:projectId/analytics-exports/:exportJobId/download', ...projectRead, controller.reporting.downloadExport)
  router.get('/api/tenants/:tenantId/projects/:projectId/report-schedules', ...projectRead, controller.reportSchedules.list)
  router.post('/api/tenants/:tenantId/projects/:projectId/report-schedules', ...projectWrite, controller.reportSchedules.create)
  router.get('/api/tenants/:tenantId/projects/:projectId/report-schedules/:scheduleId', ...projectRead, controller.reportSchedules.show)
  router.patch('/api/tenants/:tenantId/projects/:projectId/report-schedules/:scheduleId', ...projectWrite, controller.reportSchedules.update)
  router.delete('/api/tenants/:tenantId/projects/:projectId/report-schedules/:scheduleId', ...projectWrite, controller.reportSchedules.disable)
  router.post('/api/tenants/:tenantId/projects/:projectId/report-schedules/:scheduleId/runs/:runId/retry', ...projectWrite, controller.reportSchedules.retryRun)
  router.post('/api/tenants/:tenantId/projects/:projectId/data-exports', ...projectWrite, controller.lifecycle.createExport)
  router.post('/api/tenants/:tenantId/projects/:projectId/lifecycle-proofs', ...projectWrite, controller.lifecycle.createProof)
  router.get('/api/tenants/:tenantId/projects/:projectId/data-exports', ...projectRead, controller.lifecycle.listExports)
  router.get('/api/tenants/:tenantId/projects/:projectId/data-exports/:jobId', ...projectRead, controller.lifecycle.showExport)
  router.get('/api/tenants/:tenantId/projects/:projectId/data-exports/:jobId/download', ...projectRead, controller.lifecycle.downloadExport)
  router.post('/api/tenants/:tenantId/projects/:projectId/deletions', ...projectWrite, controller.lifecycle.createDeletion)
  router.get('/api/tenants/:tenantId/projects/:projectId/deletions', ...projectRead, controller.lifecycle.listDeletions)
  router.get('/api/tenants/:tenantId/projects/:projectId/deletions/:jobId', ...projectRead, controller.lifecycle.showDeletion)
  router.post('/api/tenants/:tenantId/projects/:projectId/deletion', ...projectWrite, controller.lifecycle.requestProjectDeletion)
  router.get('/api/tenants/:tenantId/projects/:projectId/deletion', ...projectRead, controller.lifecycle.showProjectDeletion)
  router.delete('/api/tenants/:tenantId/projects/:projectId/deletion', ...projectWrite, controller.lifecycle.cancelProjectDeletion)
}
